version: '3.8'

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - EXPRESS_PORT=3002
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3001,https://sns-video-generator.up.railway.app
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s