[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.railway-production"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health/simple"
healthcheckTimeout = 60
healthcheckInterval = 60
startPeriod = 180

[env]
# Node.js Configuration
NODE_VERSION = "18"
NPM_VERSION = "9"
NODE_ENV = "production"

# Next.js Configuration
NEXT_TELEMETRY_DISABLED = "1"
NEXT_OPTIMIZE_FONTS = "false"

# Application Settings
PORT = "${PORT}"
HOST = "0.0.0.0"

# 🚨 CRITICAL FIX: Supabase環境変数修正
NEXT_PUBLIC_SUPABASE_URL = "${{ NEXT_PUBLIC_SUPABASE_URL }}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${{ NEXT_PUBLIC_SUPABASE_ANON_KEY }}"
SUPABASE_SERVICE_ROLE_KEY = "${{ SUPABASE_SERVICE_ROLE_KEY }}"

# Database Configuration (from Railway variables)
DATABASE_URL = "${{ POSTGRES_URL }}"
REDIS_URL = "${{ REDIS_URL }}"

# External Services
OPENAI_API_KEY = "${{ OPENAI_API_KEY }}"
YOUTUBE_API_KEY = "${{ YOUTUBE_API_KEY }}"

# Authentication - NextAuth不使用なので削除
# NEXTAUTH_URL = "${{ RAILWAY_PUBLIC_DOMAIN ? 'https://' + RAILWAY_PUBLIC_DOMAIN : 'http://localhost:3000' }}"
# NEXTAUTH_SECRET = "${{ NEXTAUTH_SECRET }}"
# GOOGLE_CLIENT_ID = "${{ GOOGLE_CLIENT_ID }}"
# GOOGLE_CLIENT_SECRET = "${{ GOOGLE_CLIENT_SECRET }}"

# Railway-specific settings
RAILWAY_ENVIRONMENT = "production"

# Video Processing Configuration
MAX_VIDEO_SIZE = "500MB"
MAX_PROCESSING_TIME = "1800000" # 30 minutes in ms
CONCURRENT_JOBS = "3"
CHUNK_SIZE = "50MB"

# Job Queue Configuration
BULLMQ_REDIS_URL = "${{ REDIS_URL }}"
QUEUE_CONCURRENCY = "5"
JOB_ATTEMPTS = "3"
JOB_BACKOFF_DELAY = "5000"

# Webhook Configuration
WEBHOOK_SECRET = "${{ WEBHOOK_SECRET }}"
WEBHOOK_TIMEOUT = "30000"
WEBHOOK_RETRY_ATTEMPTS = "3"

# Storage Configuration
STORAGE_PROVIDER = "supabase" # supabase, s3, railway-volume
TEMP_STORAGE_PATH = "/tmp/video-processing"
MAX_STORAGE_SIZE = "10GB"

# Performance Settings
UV_THREADPOOL_SIZE = "16"
NODE_OPTIONS = "--max-old-space-size=2048"

# Monitoring & Logging
LOG_LEVEL = "info"
ENABLE_METRICS = "true"
HEALTH_CHECK_INTERVAL = "30000"

[healthcheck]
path = "/api/health/simple"
interval = 60
timeout = 30
retries = 5

[scaling]
minInstances = 1
maxInstances = 5
targetCPU = 70
targetMemory = 80

[regions]
primary = "us-west1"
fallback = ["us-east1", "eu-west1"]

[volumes]
"/tmp/video-processing" = "10GB"
"/app/uploads" = "50GB"

# Environment-specific overrides
[environments.development]
NODE_ENV = "development"
LOG_LEVEL = "debug"
CONCURRENT_JOBS = "1"
QUEUE_CONCURRENCY = "2"

[environments.staging]
NODE_ENV = "staging"
LOG_LEVEL = "debug"
CONCURRENT_JOBS = "2"
QUEUE_CONCURRENCY = "3"

[environments.production]
NODE_ENV = "production"
LOG_LEVEL = "info"
CONCURRENT_JOBS = "5"
QUEUE_CONCURRENCY = "10"

# Resource limits
[resources]
memory = "2GB"
cpu = "2vCPU"
disk = "20GB"

# Backup configuration
[backup]
enabled = true
schedule = "0 2 * * *" # Daily at 2 AM
retention = "30d"
exclude = ["/tmp/*", "/app/uploads/temp/*"]