[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.simple"
buildCommand = "npm run build"

[deploy]
# startCommand is defined in Dockerfile.simple CMD
healthcheckPath = "/api/health/simple-health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
port = 3000

[env]
NODE_ENV = "production"
PORT = "${PORT}"