# Railway configuration for static export
[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:static"

[deploy]
startCommand = "npx serve out -l $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[service]
internalPort = 3000