[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "cd .next/standalone && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
port = 3000

[env]
NODE_ENV = "production"
PORT = "${PORT}"