[build]
dockerfilePath = "Dockerfile.simple"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
port = 3000

[env]
NODE_ENV = "production"
PORT = "${PORT}"