[build]
builder = "DOCKERFILE"

[deploy]
# Dockerfileで定義されたCMDを使用（standaloneビルド対応）
# startCommandを指定しないことで、DockerfileのCMDが使われる
healthcheckPath = "/api/health/simple"

[env]
NODE_ENV = "production"
PORT = "${PORT}"